name: pretium
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.2
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/opay.png
    - assets/moniepoint.png
    - assets/palmpay.png
    - assets/opaybig.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png" # For Android adaptive icons
  adaptive_icon_background: "#FFFFFF"
